
# iframer/docker-compose.yml
services:
  devops2-iframer:
    container_name: devops2-iframer
    hostname: devops2-iframer
    image: devops2-iframer:latest
    ports:
      - "127.0.0.1:3201:80/tcp"
    #networks:
    #  - devops2-proxied-net



  # world-map-backend/docker-compose.yml
  devops2-world-map-backend:
    container_name: devops2-world-map-backend
    hostname: devops2-world-map-backend
    image: devops2-world-map-backend:latest
    depends_on:
      - devops2-iframer
    environment:
      PORT: 3202
    ports:
      - "127.0.0.1:3202:3202/tcp"
    #networks:
    #  - devops2-proxied-net



  # capitals-backend/docker-compose.yml
  devops2-capitals-backend:
    container_name: devops2-capitals-backend
    hostname: devops2-capitals-backend
    image: devops2-capitals-backend:latest
    depends_on:
      - devops2-iframer
      - devops2-capitals-db
    ports:
      - "3205:80/tcp"
    #networks:
    #  - devops2-proxied-net
    #  - devops2-db-net



  # country-info-backend/docker-compose.yml
  devops2-country-info-backend:
    container_name: devops2-country-info-backend
    hostname: devops2-country-info-backend
    image: devops2-country-info-backend:latest
    depends_on:
      - devops2-iframer
      - devops2-country-info-db
    ports:
      - "127.0.0.1:3203:80/tcp"
    volumes:
      - ./secrets:/etc/apache2/secrets
    #networks:
    #  - devops2-proxied-net
    #  - devops2-db-net



  # capitals-db/docker-compose.yml
  devops2-capitals-db:
    container_name: devops2-capitals-db
    hostname: devops2-capitals-db
    image: devops2-capitals-db:latest
    ports:
      - "27017:27017/tcp"
    #networks:
    #  - devops2-db-net



  # country-info-db/docker-compose.yml
  devops2-country-info-db:
    container_name: devops2-country-info-db
    hostname: devops2-country-info-db
    image: devops2-country-info-db:latest
    volumes:
      - ./db:/var/lib/mysql
      - ./secrets:/run/secrets
    ports:
      - "127.0.0.1:3306:3306/tcp"
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: countries-user
      MYSQL_DATABASE: countries
      MYSQL_PASSWORD_FILE: /run/secrets/countries-user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
    #networks:
    #  - devops2-db-net



#networks:
#  devops2-proxied-net:
#    external: true
#    name: devops2-proxied-net
#  devops2-db-net:
#    external: true
#    name: devops2-db-net
