
# dev-country-info-db/docker-compose.yml

services:
  devops2-dev-country-info-db:
    container_name: devops2-dev-country-info-db
    hostname: devops2-dev-country-info-db
    image: unixbirdps/devops21-metodik2-dev-country-info-db:latest
    volumes:
      - ./db:/var/lib/mysql
      - ./secrets:/run/secrets
    ports:
      - "127.0.0.1:3306:3306/tcp"
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: countries-user
      MYSQL_DATABASE: countries
      MYSQL_PASSWORD_FILE: /run/secrets/countries-user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
    #networks:
    #  - devops2-db-net

#networks:
#  devops2-db-net:
#    external: true
#    name: devops2-db-net
