
# dev-world-map-backend/docker-compose.yml

services:
  devops2-dev-world-map-backend:
    container_name: devops2-dev-world-map-backend
    hostname: devops2-dev-world-map-backend
    image: unixbirdps/devops21-metodik2-dev-world-map-backend:latest
    environment:
      PORT: 3202
    ports:
      - "127.0.0.1:3202:3202/tcp"
    #networks:
    #  - devops2-proxied-net

#networks:
#  devops2-proxied-net:
#    external: true
#    name: devops2-proxied-net
